FROM nginx:alpine

# 删除默认配置
RUN rm /etc/nginx/conf.d/default.conf

# 复制nginx配置
COPY nginx.conf /etc/nginx/conf.d/

# 复制前端文件到nginx目录
COPY public/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
