FROM node:20.18.0-alpine

# 安装 Python3 和 pip（Alpine 用 apk）
RUN apk update && \
    apk add --no-cache python3 py3-pip && \
    ln -sf python3 /usr/bin/python  # 可选：让 python 命令指向 python3

WORKDIR /app

COPY package.json .
RUN npm install --production=false

COPY . .

EXPOSE 3000

CMD ["node", "src/server.js"]